name: Modify Existing Activity
description: Request changes to an existing extracurricular activity
title: "[MODIFY]: "
labels: ["enhancement", "activity"]
assignees:
  - copilot

body:
  - type: markdown
    attributes:
      value: |
        ## Modify an Existing Activity
        Use this form to request changes to an existing activity in the system.
        
  - type: input
    id: activity-name
    attributes:
      label: Activity Name
      description: The name of the activity you want to modify
      placeholder: "Math Club"
    validations:
      required: true
      
  - type: checkboxes
    id: change-type
    attributes:
      label: What would you like to change?
      description: Select all that apply
      options:
        - label: Activity name
        - label: Description
        - label: Schedule (days/times)
        - label: Maximum participants
        - label: Category
        - label: Other (specify in details)
    validations:
      required: true
      
  - type: input
    id: new-name
    attributes:
      label: New Activity Name
      description: If changing the name, enter the new name
      placeholder: "Advanced Mathematics Club"
    validations:
      required: false
      
  - type: textarea
    id: new-description
    attributes:
      label: New Description
      description: If changing the description, enter the new text
      placeholder: "Students will explore advanced mathematical concepts and prepare for competitions."
    validations:
      required: false
      
  - type: dropdown
    id: new-days
    attributes:
      label: New Meeting Days
      description: If changing the schedule, select the new day(s)
      multiple: true
      options:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday
        - Sunday
    validations:
      required: false
      
  - type: input
    id: new-start-time
    attributes:
      label: New Start Time
      description: If changing the start time (e.g., "15:30" for 3:30 PM)
      placeholder: "15:30"
    validations:
      required: false
      
  - type: input
    id: new-end-time
    attributes:
      label: New End Time
      description: If changing the end time (e.g., "17:00" for 5:00 PM)
      placeholder: "17:00"
    validations:
      required: false
      
  - type: input
    id: new-max-participants
    attributes:
      label: New Maximum Participants
      description: If changing the participant limit, enter the new number
      placeholder: "20"
    validations:
      required: false
  
  - type: dropdown
    id: new-category
    attributes:
      label: New Activity Category
      description: If changing the category
      options:
        - Academic
        - Arts
        - Sports
        - Technology
        - Community Service
        - Other
    validations:
      required: false
      
  - type: textarea
    id: reason-for-change
    attributes:
      label: Reason for Changes
      description: Please explain why these changes are needed
      placeholder: "We need to accommodate more students due to increased interest."
    validations:
      required: true